In [1]:
from sklearn import tree
#from sklearn.cross_validation import train_test_split     NOTE:  this has changed to the following
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#%matplotlib inline

In [2]:
df = pd.read_csv('data/iris.txt', sep=",", header=None)
df.columns = ['Sepallength', 'Sepalwidth', 'Petallength', 'Petalwidth','Class']
df

      Sepallength    Sepalwidth    Petallength    Petalwidth           Class
0    sepal length   sepal width   petal length   petal width           class
1             5.1           3.5            1.4           0.2     Iris-setosa
2             4.9           3.0            1.4           0.2     Iris-setosa
3             4.7           3.2            1.3           0.2     Iris-setosa
4             4.6           3.1            1.5           0.2     Iris-setosa
..            ...           ...            ...           ...             ...
146           6.7           3.0            5.2           2.3  Iris-virginica
147           6.3           2.5            5.0           1.9  Iris-virginica
148           6.5           3.0            5.2           2.0  Iris-virginica
149           6.2           3.4            5.4           2.3  Iris-virginica
150           5.9           3.0            5.1           1.8  Iris-virginica

[151 rows x 5 columns]

In [3]:
df = df.drop([0,0])
df

    Sepallength Sepalwidth Petallength Petalwidth           Class
1           5.1        3.5         1.4        0.2     Iris-setosa
2           4.9        3.0         1.4        0.2     Iris-setosa
3           4.7        3.2         1.3        0.2     Iris-setosa
4           4.6        3.1         1.5        0.2     Iris-setosa
5           5.0        3.6         1.4        0.2     Iris-setosa
..          ...        ...         ...        ...             ...
146         6.7        3.0         5.2        2.3  Iris-virginica
147         6.3        2.5         5.0        1.9  Iris-virginica
148         6.5        3.0         5.2        2.0  Iris-virginica
149         6.2        3.4         5.4        2.3  Iris-virginica
150         5.9        3.0         5.1        1.8  Iris-virginica

[150 rows x 5 columns]

We now split our data into features (X) and response (y)

In [4]:
# define X and y
#feature_cols = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
X = df[['Sepallength', 'Sepalwidth', 'Petallength', 'Petalwidth']]
y = df['Class']

X

    Sepallength Sepalwidth Petallength Petalwidth
1           5.1        3.5         1.4        0.2
2           4.9        3.0         1.4        0.2
3           4.7        3.2         1.3        0.2
4           4.6        3.1         1.5        0.2
5           5.0        3.6         1.4        0.2
..          ...        ...         ...        ...
146         6.7        3.0         5.2        2.3
147         6.3        2.5         5.0        1.9
148         6.5        3.0         5.2        2.0
149         6.2        3.4         5.4        2.3
150         5.9        3.0         5.1        1.8

[150 rows x 4 columns]

In [5]:
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.3, random_state=42)

In [6]:
# fit a classification tree with max_depth=5
from sklearn.tree import DecisionTreeClassifier
treeclf = DecisionTreeClassifier(max_depth=5, random_state=1)

# Fit our training data
treeclf.fit(Xtrain, ytrain)

DecisionTreeClassifier(max_depth=5, random_state=1)

In [7]:
print("Training accuracy: {}".format(accuracy_score(ytrain, treeclf.predict(Xtrain))))
print("Testing accuracy : {}".format(accuracy_score(ytest, treeclf.predict(Xtest))))

Training accuracy: 0.9904761904761905
Testing accuracy : 1.0

### Stratified K-fold

In [8]:
# use crossvalidation to get avg accuracy
#from sklearn.cross_validation import cross_val_score    NOTE:  This has changed to the following
from sklearn.model_selection import cross_val_score
scores = cross_val_score(treeclf, Xtrain, ytrain, cv=10, scoring='accuracy')
print("Accuracy for each fold: {}".format(scores))
print("Mean Accuracy: {}".format(np.mean(scores)))

Accuracy for each fold: [0.90909091 0.90909091 0.90909091 0.81818182 0.81818182 1.
 1.         0.8        0.9        0.9       ]
Mean Accuracy: 0.8963636363636365

### Shuffle split

In [9]:
# use crossvalidation to get avg accuracy
#from sklearn.cross_validation import cross_val_score    NOTE:  This has changed to the following
from sklearn.model_selection import ShuffleSplit
cv = ShuffleSplit(n_splits=10, test_size=0.1, random_state=0)

shuff_scores = cross_val_score(treeclf, Xtrain, ytrain, cv=cv, scoring='accuracy')
print("Accuracy for each fold: {}".format(shuff_scores))
print("Mean Accuracy: {}".format(np.mean(shuff_scores)))

Accuracy for each fold: [1.         1.         1.         1.         1.         0.72727273
 0.90909091 1.         0.90909091 0.81818182]
Mean Accuracy: 0.9363636363636363